### ISSUE TITLE
Can we release a new gosu tag with go version 1.19

### ISSUE THREAD

**Issue by irajdeep** [tianon/gosu#118] opened 2022-11-07 11:47 UTC
Hey all

The latest release of gosu `1.14` is based on go version [1.16](https://github.com/tianon/gosu/blob/1.14/go.mod#L3). Quite a few CVEs have been fixed since that go version, could you please do a release based on the go version 1.19.

Thanks

**Comment by tianon** [comment] 2022-11-07 18:16
Sorry, this is a duplicate of #106 and #116 -- please see #104.

(Any CVE scanner reporting CVEs in the published binaries of `gosu` are likely reporting false positives; I maintain the list in #104 so that they can be reported to the relevant vendor to be flagged appropriately.)

**Closed** 2022-11-09 15:42 UTC
