### ISSUE TITLE
Groups not set on user

### ISSUE THREAD

**Issue by v-lopez** [tianon/gosu#33] opened 2017-02-24 15:07 UTC
I am using gosu on this branch: https://github.com/v-lopez/docker_images/tree/video-group

After I log in executing:
```
 docker run -it --rm -e LOCAL_USER_ID=`id -u $USER` -e LOCAL_GROUP_ID=`id -g $USER` -e LOCAL_GROUP_NAME=`id -gn $USER`  *my_image_name* bash
```

Inside the docker I execute `groups` and I only see the "user" group. But if you inspect /etc/groups the user "user" should be in the video group.

**Comment by tianon** [comment] 2017-02-24 20:36
Are you inspecting `/etc/groups` on your host, or in the container?  I don't see it being mounted in, so `gosu` can't actually read it.

**Comment by v-lopez** [comment] 2017-02-25 08:04
I inspect the one on the container.

In my dockerfile I add the user to the video group.



On Feb 24, 2017 9:36 PM, "Tianon Gravi" <notifications@github.com> wrote:

Are you inspecting /etc/groups on your host, or in the container? I don't
see it being mounted in, so gosu can't actually read it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tianon/gosu/issues/33#issuecomment-282397973>, or mute
the thread

**Comment by tianon** [comment] 2017-02-28 22:40
Hmm, ok; are you using the `user:group` syntax, or just `user` ?  IIRC, only the latter will inherit supplementary groups, because the former is effectively saying "I explicitly want _only_ this user+group, no automatic additional behavior."

**Comment by v-lopez** [comment] 2017-03-01 06:32
I am using user:group, I will try their other and post the results.

Thanks!

**Comment by v-lopez** [comment] 2017-03-01 10:09
You are right, problem solved.

Maybe this could be explained explicitely in the documentation.

Thanks for this awesome tool.

**Comment by tianon** [comment] 2018-10-15 22:33
Closing given that this is essentially by design -- see https://github.com/tianon/gosu/blob/fd64f11edb4fa2423859d615aa8783df62a4be40/Dockerfile.test#L25-L67 for our (pretty extensive) test suite of edge cases.

I agree that this would be a good idea to document better, but this is fundamentally Docker (and at this point even `runc` specific) functionality, so I think the associated documentation belongs in one of those upstream projects (our `README.md` here explicitly calls out that our syntax is that of Docker's own `docker run --user` flag, using the very same implementation referenced directly from `runc`'s code).

**Closed by tianon** 2018-10-15 22:33 UTC
