### ISSUE TITLE
The key is not certified with a trusted signature in Debian stretch

### ISSUE THREAD

**Issue by eleidan** [tianon/gosu#38] opened 2017-07-06 20:59 UTC
**How to reproduce**
Issue the following command on **Debian 9 (stretch)** official container as root user:
```
apt-get update && apt-get install -y --no-install-recommends \
      gnupg \
      dirmngr \
    && dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" \
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/1.10/gosu-$dpkgArch" \
    && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/1.10/gosu-$dpkgArch.asc" \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
    && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true
```

As a result, an output similar to the following is expected:
```
gpg: keybox '/tmp/tmp.J52ezIfr5l/pubring.kbx' created
gpg: /tmp/tmp.J52ezIfr5l/trustdb.gpg: trustdb created
gpg: key 036A9C25BF357DD4: public key "Tianon Gravi <tianon@tianon.xyz>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Wed Sep 28 22:22:56 2016 UTC
gpg:                using RSA key 036A9C25BF357DD4
gpg: Good signature from "Tianon Gravi <tianon@tianon.xyz>" [unknown]
gpg:                 aka "Tianon Gravi <tianon@debian.org>" [unknown]
gpg:                 aka "Tianon Gravi <tianon@dockerproject.org>" [unknown]
gpg:                 aka "Andrew Page (tianon) <andrew@infosiftr.com>" [unknown]
gpg:                 aka "Andrew Page (tianon) <andrew@vitalroute.com>" [unknown]
gpg:                 aka "Andrew Page (Tianon Gravi) <admwiggin@gmail.com>" [unknown]
gpg:                 aka "Tianon Gravi (Andrew Page) <tianon@infosiftr.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B42F 6819 007F 00F8 8E36  4FD4 036A 9C25 BF35 7DD4
```

**Comment by tianon** [comment] 2017-07-06 21:10
That's normal -- this warning simply means that when the key was imported, it wasn't marked as "trusted", but the output clearly notes that the file _is_ properly signed with that key. :+1:

**Comment by eleidan** [comment] 2017-07-06 21:27
Thank you for the response, but that breaks my automation builds on DockerHub because of that error.

**Comment by tianon** [comment] 2017-07-06 21:28
I see a warning, but not an error -- can you please provide the full build output of the step?

**Comment by tianon** [comment] 2017-07-06 21:30
For example, I cannot reproduce any errors with the following:

```dockerfile
FROM debian:stretch-slim
ENV GOSU_VERSION 1.10
RUN set -ex; \
	\
	fetchDeps=' \
		ca-certificates \
		wget \
		gnupg2 dirmngr \
	'; \
	apt-get update; \
	apt-get install -y --no-install-recommends $fetchDeps; \
	rm -rf /var/lib/apt/lists/*; \
	\
	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
	\
# verify the signature
	export GNUPGHOME="$(mktemp -d)"; \
	gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
	rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; \
	\
	chmod +x /usr/local/bin/gosu; \
# verify that the binary works
	gosu nobody true; \
	\
	apt-get purge -y --auto-remove $fetchDeps
```

**Comment by tianon** [comment] 2017-07-06 21:31
Additionally, `gosu` is packaged in Stretch, so you could simply install via `apt-get` instead if you'd rather: https://packages.debian.org/stretch/gosu

**Comment by eleidan** [comment] 2017-07-06 21:34
That rocks!!! Thank you! :+1:

**Comment by eleidan** [comment] 2017-07-06 21:39
@tianon That works on local host, but fails with error on **DockerHub** :confused: 
Anyway, installing `gosu` from repos work like a charm :wink:

**Comment by tianon** [comment] 2017-07-06 21:40
Glad to hear it! :+1:

**Closed by tianon** 2017-07-06 21:40 UTC
